### ISSUE TITLE
totem assert failure: totem: totem: gen9_mfd.c:649: gen9_hcpd_get_reference_picture_frame_id: Assertion `0' failed.

### ISSUE THREAD

**Issue by ejsc1** [intel/intel-vaapi-driver#451]
Open bug in launchpad.net https://bugs.launchpad.net/bugs/1821525

"Watching movie 4k."

BackTrace:
```
#0  __GI_raise (sig=sig@entry=6) at ../sysdeps/unix/sysv/linux/raise.c:50
        set = {__val = {0, 139667910656424, 4222451712, 139666431533520, 139666431533520, 139666431533520, 139666431533520, 139666431533619, 139666431533620, 139666431533520, 139666431533620, 0, 0, 0, 0, 0}}
        pid = <optimized out>
        tid = <optimized out>
        ret = <optimized out>
#1  0x00007f06f82d2535 in __GI_abort () at abort.c:79
        save_stage = 1
        act = {__sigaction_handler = {sa_handler = 0x7f06a009e1d0, sa_sigaction = 0x7f06a009e1d0}, sa_mask = {__val = {0, 139666430885920, 4294967295, 0, 0, 0, 21474836480, 139666758029096, 139666758028944, 139667817901418, 139667817901418, 0, 12451935558776453120, 139667911854567, 0, 139667817901418}}, sa_flags = -1298457392, sa_restorer = 0x7f06b2cbcba4}
        sigs = {__val = {32, 0 <repeats 15 times>}}
#2  0x00007f06f82d240f in __assert_fail_base (fmt=0x7f06f2ac2d6a <error: Cannot access memory at address 0x7f06f2ac2d6a>, assertion=0x7f06b2cbcba4 "0", file=0x7f06b29b1cd0 "gen9_mfd.c", line=649, function=<optimized out>) at assert.c:92
        str = 0x7f06a009e1d0 "\220\335\a\240\006\177"
        total = 4096
#3  0x00007f06f82e1fb2 in __GI___assert_fail (assertion=assertion@entry=0x7f06b2cbcba4 "0", file=file@entry=0x7f06b29b1cd0 "gen9_mfd.c", line=line@entry=649, function=function@entry=0x7f06b29b23e0 <__PRETTY_FUNCTION__.14793> "gen9_hcpd_get_reference_picture_frame_id") at assert.c:101
No locals.
#4  0x00007f06b287af94 in gen9_hcpd_get_reference_picture_frame_id (frame_store=frame_store@entry=0x7f06a0079a70, ref_pic=<optimized out>, ref_pic=<optimized out>) at gen9_mfd.c:649
        i = <optimized out>
        __PRETTY_FUNCTION__ = "gen9_hcpd_get_reference_picture_frame_id"
#5  0x00007f06b287c94f in gen9_hcpd_get_collocated_ref_idx (ctx=0x7f06a80b8cf0, gen9_hcpd_context=0x7f06a0079a40, slice_param=0x7f06a0013a30, pic_param=0x7f06a00a08f0) at gen9_mfd.c:806
        ref_list = <optimized out>
        ref_pic = <optimized out>
        ref_list = <optimized out>
        ref_pic = <optimized out>
        __PRETTY_FUNCTION__ = "gen9_hcpd_get_collocated_ref_idx"
#6  gen9_hcpd_slice_state (ctx=0x7f06a80b8cf0, gen9_hcpd_context=0x7f06a0079a40, next_slice_param=0x7f06a00080e0, slice_param=0x7f06a0013a30, pic_param=0x7f06a00a08f0) at gen9_mfd.c:878
        slice_hor_pos = 0
        slice_ver_pos = 0
        collocated_ref_idx = <optimized out>
        collocated_from_l0_flag = <optimized out>
        sliceqp = 0
        batch = 0x7f06a000be80
        next_slice_hor_pos = 0
        next_slice_ver_pos = 8
        sliceqp_sign_flag = 0
        batch = <optimized out>
        slice_hor_pos = <optimized out>
        slice_ver_pos = <optimized out>
        next_slice_hor_pos = <optimized out>
        next_slice_ver_pos = <optimized out>
        collocated_ref_idx = <optimized out>
        collocated_from_l0_flag = <optimized out>
        sliceqp_sign_flag = <optimized out>
        sliceqp = <optimized out>
        __PRETTY_FUNCTION__ = "gen9_hcpd_slice_state"
#7  gen9_hcpd_hevc_decode_picture (ctx=0x7f06a80b8cf0, decode_state=0x7f06a80c7c68, gen9_hcpd_context=0x7f06a0079a40) at gen9_mfd.c:1027
        vaStatus = 0
        i965 = 0x7f06a80c5600
        batch = 0x7f06a000be80
        pic_param = 0x7f06a00a08f0
        slice_param = 0x7f06a0013a30
        next_slice_param = 0x7f06a00080e0
        next_slice_group_param = 0x7f06a00080e0
        slice_data_bo = <optimized out>
        i = 0
        j = 0
        __PRETTY_FUNCTION__ = "gen9_hcpd_hevc_decode_picture"
#8  0x00007f06d46222e0 in vaEndPicture (dpy=dpy@entry=0x7f06a80b8b80, context=context@entry=33554433) at va.c:1519
        va_status = 0
        ctx = 0x7f06a80b8cf0
#9  0x00007f06d468650e in gst_vaapi_picture_decode (picture=picture@entry=0x7f06a00a6550) at ../../../../gst-libs/gst/vaapi/gstvaapidecoder_objects.c:308
        iq_matrix = <optimized out>
        bitplane = <optimized out>
        huf_table = <optimized out>
        prob_table = <optimized out>
        va_display = 0x7f06a80b8b80
        va_context = 33554433
        status = <optimized out>
        i = <optimized out>
        __FUNCTION__ = "gst_vaapi_picture_decode"
        __func__ = "gst_vaapi_picture_decode"
#10 0x00007f06d469cd5d in decode_current_picture (decoder=0x7f06a80f4f20) at ../../../../gst-libs/gst/vaapi/gstvaapidecoder_h265.c:1315
        priv = 0x7f06a80f5020
        picture = <optimized out>
#11 0x00007f06d4677148 in do_decode_1 (decoder=decoder@entry=0x7f06a80f4f20, frame=frame@entry=0x7f06a8009950) at ../../../../gst-libs/gst/vaapi/gstvaapidecoder.c:259
        klass = 0x7f06a80d3980
        status = <optimized out>
#12 0x00007f06d46786ff in do_decode (base_frame=0x7f06a84250a0, decoder=0x7f06a80f4f20) at ../../../../gst-libs/gst/vaapi/gstvaapidecoder.c:287
        ps = 0x7f06a80f4fb8
        frame = 0x7f06a8009950
        status = <optimized out>
        ps = <optimized out>
        frame = <optimized out>
        status = <optimized out>
#13 gst_vaapi_decoder_decode (decoder=0x7f06a80f4f20, frame=frame@entry=0x7f06a84250a0) at ../../../../gst-libs/gst/vaapi/gstvaapidecoder.c:1046
        status = GST_VAAPI_DECODER_STATUS_SUCCESS
        __FUNCTION__ = "gst_vaapi_decoder_decode"
#14 0x00007f06d465a8c8 in gst_vaapidecode_handle_frame (frame=<optimized out>, vdec=<optimized out>) at ../../../gst/vaapi/gstvaapidecode.c:708
        decode = <optimized out>
        status = <optimized out>
        ret = <optimized out>
        decode = <optimized out>
        status = <optimized out>
        ret = <optimized out>
        __func__ = "gst_vaapidecode_handle_frame"
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        __txt = <optimized out>
        __dbg = <optimized out>
        __dec = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
#15 gst_vaapidecode_handle_frame (vdec=0x7f06a8091af0, frame=0x7f06a84250a0) at ../../../gst/vaapi/gstvaapidecode.c:696
        decode = 0x7f06a8091af0
        status = <optimized out>
        __func__ = "gst_vaapidecode_handle_frame"
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        __txt = <optimized out>
        __dbg = <optimized out>
        __dec = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
#16 0x00007f06f8194f0b in gst_video_decoder_decode_frame (decoder=decoder@entry=0x7f06a8091af0, frame=0x7f06a84250a0) at gstvideodecoder.c:3402
        priv = 0x7f06a8091950
        decoder_class = 0x7f06a809a0d0
        ret = GST_FLOW_OK
        __FUNCTION__ = "gst_video_decoder_decode_frame"
        __PRETTY_FUNCTION__ = "gst_video_decoder_decode_frame"
#17 0x00007f06f819dc5a in gst_video_decoder_have_frame (decoder=decoder@entry=0x7f06a8091af0) at gstvideodecoder.c:3334
        priv = <optimized out>
        buffer = <optimized out>
        n_available = 220580
        pts = <optimized out>
        dts = <optimized out>
        duration = <optimized out>
        flags = <optimized out>
        ret = GST_FLOW_OK
        __PRETTY_FUNCTION__ = "gst_video_decoder_have_frame"
#18 0x00007f06d465a39a in gst_vaapidecode_parse_frame (at_eos=0, adapter=0x7f06a801e000, frame=0x7f06a84250a0, vdec=0x7f06a8091af0) at ../../../gst/vaapi/gstvaapidecode.c:1150
        decode = 0x7f06a8091af0
        status = <optimized out>
        ret = <optimized out>
        got_unit_size = 42340
        got_frame = 1
        decode = <optimized out>
        status = <optimized out>
        ret = <optimized out>
        got_unit_size = <optimized out>
        got_frame = <optimized out>
        __func__ = "gst_vaapidecode_parse_frame"
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
#19 gst_vaapidecode_parse (vdec=0x7f06a8091af0, frame=0x7f06a84250a0, adapter=0x7f06a801e000, at_eos=0) at ../../../gst/vaapi/gstvaapidecode.c:1187
        ret = <optimized out>
#20 0x00007f06f81973f7 in gst_video_decoder_parse_available (dec=dec@entry=0x7f06a8091af0, at_eos=at_eos@entry=0, new_buffer=0, new_buffer@entry=1) at gstvideodecoder.c:893
        decoder_class = 0x7f06a809a0d0
        priv = 0x7f06a8091950
        ret = GST_FLOW_OK
        was_available = 220580
        available = 220580
        inactive = 0
        __PRETTY_FUNCTION__ = "gst_video_decoder_parse_available"
#21 0x00007f06f819a11c in gst_video_decoder_chain_forward (decoder=decoder@entry=0x7f06a8091af0, buf=buf@entry=0x7f06a800c4f0, at_eos=at_eos@entry=0) at gstvideodecoder.c:2139
        priv = 0x7f06a8091950
        klass = <optimized out>
        ret = GST_FLOW_OK
        __FUNCTION__ = "gst_video_decoder_chain_forward"
        __PRETTY_FUNCTION__ = "gst_video_decoder_chain_forward"
#22 0x00007f06f819a761 in gst_video_decoder_chain (pad=<optimized out>, parent=<optimized out>, buf=0x7f06a800c4f0) at gstvideodecoder.c:2438
        decoder = 0x7f06a8091af0
        ret = GST_FLOW_OK
        __PRETTY_FUNCTION__ = "gst_video_decoder_chain"
#23 0x00007f06f8081942 in gst_pad_chain_data_unchecked (data=0x7f06a800c4f0, type=4112, pad=0x7f06ac18d890) at gstpad.c:4326
        chainfunc = 0x7f06f819a430 <gst_video_decoder_chain>
        chainfunc = <optimized out>
        parent = 0x7f06a8091af0
        ret = <optimized out>
        handled = 0
        ret = <optimized out>
        parent = <optimized out>
        handled = <optimized out>
        __FUNCTION__ = "gst_pad_chain_data_unchecked"
        __PRETTY_FUNCTION__ = "gst_pad_chain_data_unchecked"
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        info = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        info = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        chainfunc = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        chainlistfunc = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
#24 gst_pad_push_data (pad=pad@entry=0x560fb117bcf0, type=type@entry=4112, data=data@entry=0x7f06a800c4f0) at gstpad.c:4582
        peer = 0x7f06ac18d890
        ret = GST_FLOW_OK
        handled = 0
        __FUNCTION__ = "gst_pad_push_data"
        __PRETTY_FUNCTION__ = "gst_pad_push_data"
#25 0x00007f06f8088282 in gst_pad_push (pad=pad@entry=0x560fb117bcf0, buffer=buffer@entry=0x7f06a800c4f0) at gstpad.c:4701
        res = <optimized out>
        __FUNCTION__ = "gst_pad_push"
#26 0x00007f06f806df3b in gst_proxy_pad_chain_default (pad=<optimized out>, parent=<optimized out>, buffer=0x7f06a800c4f0) at gstghostpad.c:127
        res = <optimized out>
        internal = 0x560fb117bcf0
        __FUNCTION__ = "gst_proxy_pad_chain_default"
#27 0x00007f06f8081942 in gst_pad_chain_data_unchecked (data=0x7f06a800c4f0, type=4112, pad=0x560fb1178b90) at gstpad.c:4326
        chainfunc = 0x7f06f806de80 <gst_proxy_pad_chain_default>
        chainfunc = <optimized out>
        parent = 0x560fb11b77a0
        ret = <optimized out>
        handled = 0
        ret = <optimized out>
        parent = <optimized out>
        handled = <optimized out>
        __FUNCTION__ = "gst_pad_chain_data_unchecked"
        __PRETTY_FUNCTION__ = "gst_pad_chain_data_unchecked"
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        info = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        info = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        chainfunc = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        chainlistfunc = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
#28 gst_pad_push_data (pad=pad@entry=0x7f06ac18d640, type=type@entry=4112, data=data@entry=0x7f06a800c4f0) at gstpad.c:4582
        peer = 0x560fb1178b90
        ret = GST_FLOW_OK
        handled = 0
        __FUNCTION__ = "gst_pad_push_data"
        __PRETTY_FUNCTION__ = "gst_pad_push_data"
#29 0x00007f06f8088282 in gst_pad_push (pad=0x7f06ac18d640, buffer=0x7f06a800c4f0) at gstpad.c:4701
        res = <optimized out>
        __FUNCTION__ = "gst_pad_push"
#30 0x00007f06f6ec50ed in gst_base_transform_chain (pad=<optimized out>, parent=0x560fb10a2ec0, buffer=<optimized out>) at gstbasetransform.c:2330
        position_out = <optimized out>
        trans = 0x560fb10a2ec0
        klass = 0x560fb11a22e0
        priv = 0x560fb10a2df0
        ret = <optimized out>
        position = 1691648708333
        timestamp = <optimized out>
        duration = <optimized out>
        outbuf = 0x7f06a800c4f0
        __PRETTY_FUNCTION__ = "gst_base_transform_chain"
#31 0x00007f06f8081942 in gst_pad_chain_data_unchecked (data=0x7f06a800c4f0, type=4112, pad=0x7f06ac18d3f0) at gstpad.c:4326
        chainfunc = 0x7f06f6ec4f20 <gst_base_transform_chain>
        chainfunc = <optimized out>
        parent = 0x560fb10a2ec0
        ret = <optimized out>
        handled = 0
        ret = <optimized out>
        parent = <optimized out>
        handled = <optimized out>
        __FUNCTION__ = "gst_pad_chain_data_unchecked"
        __PRETTY_FUNCTION__ = "gst_pad_chain_data_unchecked"
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        info = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        info = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        chainfunc = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        chainlistfunc = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
#32 gst_pad_push_data (pad=pad@entry=0x7f06ac18d1a0, type=type@entry=4112, data=data@entry=0x7f06a800c4f0) at gstpad.c:4582
        peer = 0x7f06ac18d3f0
        ret = GST_FLOW_OK
        handled = 0
        __FUNCTION__ = "gst_pad_push_data"
        __PRETTY_FUNCTION__ = "gst_pad_push_data"
#33 0x00007f06f8088282 in gst_pad_push (pad=0x7f06ac18d1a0, buffer=buffer@entry=0x7f06a800c4f0) at gstpad.c:4701
        res = <optimized out>
        __FUNCTION__ = "gst_pad_push"
#34 0x00007f06f6ea8b47 in gst_base_parse_push_frame (parse=parse@entry=0x7f06a8021af0, frame=frame@entry=0x7f06b37fd880) at gstbaseparse.c:2580
        ret = GST_FLOW_OK
        last_start = <optimized out>
        last_stop = 1691648708333
        klass = <optimized out>
        buffer = 0x7f06a800c4f0
        size = 220580
        __FUNCTION__ = "gst_base_parse_push_frame"
        __PRETTY_FUNCTION__ = "gst_base_parse_push_frame"
#35 0x00007f06f6ea9bb5 in gst_base_parse_chain (pad=<optimized out>, parent=<optimized out>, buffer=0x7f06a800c4f0) at gstbaseparse.c:3202
        frame = {buffer = 0x0, out_buffer = 0x0, flags = 0, offset = 0, overhead = 0, size = 0, _gst_reserved_i = {0, 0}, _gst_reserved_p = {0x0, 0x0}, _private_flags = 1}
        bclass = <optimized out>
        parse = 0x7f06a8021af0
        ret = GST_FLOW_OK
        old_ret = GST_FLOW_OK
        tmpbuf = 0x0
        skip = -1
        min_size = <optimized out>
        av = <optimized out>
        pts = <optimized out>
        dts = <optimized out>
        __PRETTY_FUNCTION__ = "gst_base_parse_chain"
#36 0x00007f06f8081942 in gst_pad_chain_data_unchecked (data=0x7f06a800c4f0, type=4112, pad=0x7f06ac18cf50) at gstpad.c:4326
        chainfunc = 0x7f06f6ea8fe0 <gst_base_parse_chain>
        chainfunc = <optimized out>
        parent = 0x7f06a8021af0
        ret = <optimized out>
        handled = 0
        ret = <optimized out>
        parent = <optimized out>
        handled = <optimized out>
        __FUNCTION__ = "gst_pad_chain_data_unchecked"
        __PRETTY_FUNCTION__ = "gst_pad_chain_data_unchecked"
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        info = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        info = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        chainfunc = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        chainlistfunc = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
#37 gst_pad_push_data (pad=pad@entry=0x7f06ac18cd00, type=type@entry=4112, data=data@entry=0x7f06a800c4f0) at gstpad.c:4582
        peer = 0x7f06ac18cf50
        ret = GST_FLOW_OK
        handled = 0
        __FUNCTION__ = "gst_pad_push_data"
        __PRETTY_FUNCTION__ = "gst_pad_push_data"
#38 0x00007f06f8088282 in gst_pad_push (pad=0x7f06ac18cd00, buffer=buffer@entry=0x7f06a800c4f0) at gstpad.c:4701
        res = <optimized out>
        __FUNCTION__ = "gst_pad_push"
#39 0x00007f06f00631dd in gst_single_queue_push_one (allow_drop=<synthetic pointer>, object=0x7f06a800c4f0, sq=0x7f06a801d020, mq=0x560fb17f1de0) at gstmultiqueue.c:1639
        buffer = 0x7f06a800c4f0
        timestamp = 1691607000000
        duration = <optimized out>
        result = GST_FLOW_OK
        result = <optimized out>
        __PRETTY_FUNCTION__ = "gst_single_queue_push_one"
        buffer = <optimized out>
        timestamp = <optimized out>
        duration = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        event = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
        query = <optimized out>
        res = <optimized out>
        _g_boolean_var_ = <optimized out>
        _g_boolean_var_ = <optimized out>
#40 gst_multi_queue_loop (pad=<optimized out>) at gstmultiqueue.c:1959
        sq = 0x7f06a801d020
        item = <optimized out>
        sitem = 0x7f06a0009b60
        mq = 0x560fb17f1de0
        object = <optimized out>
        newid = 96628
        result = <optimized out>
        next_time = <optimized out>
        is_buffer = 1
        do_update_buffering = 0
        dropping = 0
        __PRETTY_FUNCTION__ = "gst_multi_queue_loop"
#41 0x00007f06f80b6321 in gst_task_func (task=0x560fb1623cb0) at gsttask.c:328
        lock = 0x7f06ac18cd70
        tself = 0x7f06a8014e30
        priv = 0x560fb1623c60
        __PRETTY_FUNCTION__ = "gst_task_func"
#42 0x00007f06f8f40353 in g_thread_pool_thread_proxy (data=<optimized out>) at ../../../glib/gthreadpool.c:308
        task = 0x560fb12757c0
        pool = 0x560fb0b416e0
#43 0x00007f06f8f3f98d in g_thread_proxy (data=0x7f06a8014e30) at ../../../glib/gthread.c:805
        thread = 0x7f06a8014e30
        __FUNCTION__ = "g_thread_proxy"
        _g_boolean_var_ = <optimized out>
#44 0x00007f06f7817182 in start_thread (arg=<optimized out>) at pthread_create.c:486
        ret = <optimized out>
        pd = <optimized out>
        now = <optimized out>
        unwind_buf = {cancel_jmp_buf = {{jmp_buf = {139666758035200, 7490950053542788013, 139666766420622, 139666766420623, 139666766420768, 139666758032448, -7352032257867220051, -7351884085033141331}, mask_was_saved = 0}}, priv = {pad = {0x0, 0x0, 0x0, 0x0}, data = {prev = 0x0, cleanup = 0x0, canceltype = 0}}}
        not_first_call = <optimized out>
#45 0x00007f06f83cafaf in clone () at ../sysdeps/unix/sysv/linux/x86_64/clone.S:95
No locals.
```

**Comment by ejsc1** [comment]
I can always reproduce is error.

**Comment by vanvugt** [comment]
Duplicate of #448.
